# Generated by Django 2.1.5 on 2019-02-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0005_auto_20190212_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user_profile',
        ),
        migrations.RenameField(
            model_name='feedmenueplan',
            old_name='created_on',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='feedmenueplan',
            name='PLU',
        ),
        migrations.RemoveField(
            model_name='feedmenueplan',
            name='category',
        ),
        migrations.AddField(
            model_name='feedmenueplan',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
