# Generated by Django 2.1.5 on 2019-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0006_auto_20190212_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmenueplan',
            name='transaction_id',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
