# Generated by Django 2.1.5 on 2019-02-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0007_feedmenueplan_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmenueplan',
            name='title',
        ),
        migrations.AddField(
            model_name='feedmenueplan',
            name='PLU',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='feedmenueplan',
            name='component',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedmenueplan',
            name='date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AddField(
            model_name='feedmenueplan',
            name='menueline',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
    ]
