# Generated by Django 2.1.5 on 2019-02-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0008_auto_20190214_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSubstitutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLU', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top8', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top9', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
